# Generated by Django 5.0.2 on 2024-02-12 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_old_price', models.FloatField()),
                ('product_new_price', models.FloatField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='adminpanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='product_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image_all', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='adminpanel.product')),
            ],
        ),
    ]
