# Generated by Django 5.0.2 on 2024-03-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
